### ISSUE TITLE
Directory does not exist...

### ISSUE THREAD

**Issue by JFelton** [Iristyle/Posh-GitHub#10]
fatal: could not create work tree dir 'C:\Users\JFelton.EASTPOINT\Documents\WindowsPowerShell\Modules\posh-github'.: No
such file or directory

**Comment by JFelton** [comment]
Work around:
I manually created the 
Documents\WindowsPowerShell\Modules
directories and everything is working w/ the powerscript copied from the readme.

**Comment by Iristyle** [comment]
Using Choc to install now...
